---
- name: Install common software requirements
  ignore_errors: yes
  become: true
  yum: pkg={{ item }} state=present
  with_items:
    - epel-release
    - serverbackup-enterprise-agent
    - libselinux
    - ufw
    - telnet
    - vim
    - kernel-devel
    - kernel-headers
    - perl
    - gcc
    - bzip2

